name: flutter_octicons
description: Easily integrate GitHub's Octicons in your own Flutter project.
version: 1.44.0
homepage: https://github.com/Coronon/flutter_octicons

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  yaml: ^3.1.0

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Octicons12
      fonts:
        - asset: lib/fonts/octicons12.ttf
    - family: Octicons16
      fonts:
        - asset: lib/fonts/octicons16.ttf
    - family: Octicons24
      fonts:
        - asset: lib/fonts/octicons24.ttf
    - family: Octicons48
      fonts:
        - asset: lib/fonts/octicons48.ttf
    - family: Octicons96
      fonts:
        - asset: lib/fonts/octicons96.ttf
