name: flutter_octicons
description: Easily integrate GitHub's Octicons in your own Flutter project.
version: 0.2.0
homepage: https://github.com/Coronon/flutter_octicons

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  yaml: ^3.1.0

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Octicons
      fonts:
        - asset: lib/fonts/octicons.ttf
