name: flutter_octicons
description: GitHub's Octicons for Flutter.
version: 0.0.1
homepage: https://pub.dev/packages/flutter_octicons

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  yaml: ^3.1.0

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Octicons
      fonts:
        - asset: lib/fonts/octicons.ttf
