// ignore_for_file: constant_identifier_names
library flutter_octicons;

import 'package:flutter/widgets.dart';

class OctIcons {
  // No constructor
  OctIcons._();

  static const _fontFamily = 'Octicons';
  static const _fontPackage = 'flutter_octicons';

  // Icons
  static const IconData accessibility_16 =
      IconData(0xf101, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData alert_16 =
      IconData(0xf102, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData alert_24 =
      IconData(0xf103, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData alert_fill_12 =
      IconData(0xf104, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData apps_16 =
      IconData(0xf105, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData archive_16 =
      IconData(0xf106, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData archive_24 =
      IconData(0xf107, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_both_16 =
      IconData(0xf108, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_both_24 =
      IconData(0xf109, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_down_16 =
      IconData(0xf10a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_down_24 =
      IconData(0xf10b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_down_left_24 =
      IconData(0xf10c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_down_right_24 =
      IconData(0xf10d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_left_16 =
      IconData(0xf10e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_left_24 =
      IconData(0xf10f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_right_16 =
      IconData(0xf110, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_right_24 =
      IconData(0xf111, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_switch_16 =
      IconData(0xf112, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_switch_24 =
      IconData(0xf113, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_up_16 =
      IconData(0xf114, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_up_24 =
      IconData(0xf115, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_up_left_24 =
      IconData(0xf116, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData arrow_up_right_24 =
      IconData(0xf117, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData beaker_16 =
      IconData(0xf118, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData beaker_24 =
      IconData(0xf119, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bell_16 =
      IconData(0xf11a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bell_24 =
      IconData(0xf11b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bell_fill_16 =
      IconData(0xf11c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bell_fill_24 =
      IconData(0xf11d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bell_slash_16 =
      IconData(0xf11e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bell_slash_24 =
      IconData(0xf11f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData blocked_16 =
      IconData(0xf120, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData blocked_24 =
      IconData(0xf121, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bold_16 =
      IconData(0xf122, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bold_24 =
      IconData(0xf123, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData book_16 =
      IconData(0xf124, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData book_24 =
      IconData(0xf125, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bookmark_16 =
      IconData(0xf126, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bookmark_24 =
      IconData(0xf127, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bookmark_fill_24 =
      IconData(0xf128, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bookmark_slash_16 =
      IconData(0xf129, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bookmark_slash_24 =
      IconData(0xf12a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bookmark_slash_fill_24 =
      IconData(0xf12b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData briefcase_16 =
      IconData(0xf12c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData briefcase_24 =
      IconData(0xf12d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData broadcast_16 =
      IconData(0xf12e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData broadcast_24 =
      IconData(0xf12f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData browser_16 =
      IconData(0xf130, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData browser_24 =
      IconData(0xf131, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bug_16 =
      IconData(0xf132, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData bug_24 =
      IconData(0xf133, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData calendar_16 =
      IconData(0xf134, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData calendar_24 =
      IconData(0xf135, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData check_16 =
      IconData(0xf136, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData check_24 =
      IconData(0xf137, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData check_circle_16 =
      IconData(0xf138, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData check_circle_24 =
      IconData(0xf139, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData check_circle_fill_12 =
      IconData(0xf13a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData check_circle_fill_16 =
      IconData(0xf13b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData check_circle_fill_24 =
      IconData(0xf13c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData checklist_16 =
      IconData(0xf13d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData checklist_24 =
      IconData(0xf13e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_down_16 =
      IconData(0xf13f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_down_24 =
      IconData(0xf140, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_left_16 =
      IconData(0xf141, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_left_24 =
      IconData(0xf142, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_right_16 =
      IconData(0xf143, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_right_24 =
      IconData(0xf144, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_up_16 =
      IconData(0xf145, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData chevron_up_24 =
      IconData(0xf146, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData circle_16 =
      IconData(0xf147, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData circle_24 =
      IconData(0xf148, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData circle_slash_16 =
      IconData(0xf149, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData circle_slash_24 =
      IconData(0xf14a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData clock_16 =
      IconData(0xf14b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData clock_24 =
      IconData(0xf14c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData cloud_16 =
      IconData(0xf14d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData cloud_24 =
      IconData(0xf14e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData cloud_offline_16 =
      IconData(0xf14f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData cloud_offline_24 =
      IconData(0xf150, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData code_16 =
      IconData(0xf151, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData code_24 =
      IconData(0xf152, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData code_of_conduct_16 =
      IconData(0xf153, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData code_of_conduct_24 =
      IconData(0xf154, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData code_review_16 =
      IconData(0xf155, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData code_review_24 =
      IconData(0xf156, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData code_square_16 =
      IconData(0xf157, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData code_square_24 =
      IconData(0xf158, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData codescan_16 =
      IconData(0xf159, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData codescan_24 =
      IconData(0xf15a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData codescan_checkmark_16 =
      IconData(0xf15b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData codescan_checkmark_24 =
      IconData(0xf15c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData codespaces_16 =
      IconData(0xf15d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData codespaces_24 =
      IconData(0xf15e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData columns_16 =
      IconData(0xf15f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData columns_24 =
      IconData(0xf160, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData comment_16 =
      IconData(0xf161, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData comment_24 =
      IconData(0xf162, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData comment_discussion_16 =
      IconData(0xf163, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData comment_discussion_24 =
      IconData(0xf164, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData commit_24 =
      IconData(0xf165, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData container_16 =
      IconData(0xf166, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData container_24 =
      IconData(0xf167, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData copy_16 =
      IconData(0xf168, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData copy_24 =
      IconData(0xf169, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData cpu_16 =
      IconData(0xf16a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData cpu_24 =
      IconData(0xf16b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData credit_card_16 =
      IconData(0xf16c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData credit_card_24 =
      IconData(0xf16d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData cross_reference_16 =
      IconData(0xf16e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData cross_reference_24 =
      IconData(0xf16f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData dash_16 =
      IconData(0xf170, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData dash_24 =
      IconData(0xf171, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData database_16 =
      IconData(0xf172, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData database_24 =
      IconData(0xf173, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData dependabot_16 =
      IconData(0xf174, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData dependabot_24 =
      IconData(0xf175, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData desktop_download_16 =
      IconData(0xf176, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData desktop_download_24 =
      IconData(0xf177, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData device_camera_16 =
      IconData(0xf178, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData device_camera_video_16 =
      IconData(0xf179, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData device_camera_video_24 =
      IconData(0xf17a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData device_desktop_16 =
      IconData(0xf17b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData device_desktop_24 =
      IconData(0xf17c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData device_mobile_16 =
      IconData(0xf17d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData device_mobile_24 =
      IconData(0xf17e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData diamond_16 =
      IconData(0xf17f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData diamond_24 =
      IconData(0xf180, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData diff_16 =
      IconData(0xf181, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData diff_24 =
      IconData(0xf182, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData diff_added_16 =
      IconData(0xf183, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData diff_ignored_16 =
      IconData(0xf184, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData diff_modified_16 =
      IconData(0xf185, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData diff_removed_16 =
      IconData(0xf186, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData diff_renamed_16 =
      IconData(0xf187, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData dot_16 =
      IconData(0xf188, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData dot_24 =
      IconData(0xf189, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData dot_fill_16 =
      IconData(0xf18a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData dot_fill_24 =
      IconData(0xf18b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData download_16 =
      IconData(0xf18c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData download_24 =
      IconData(0xf18d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData duplicate_16 =
      IconData(0xf18e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData duplicate_24 =
      IconData(0xf18f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData ellipsis_16 =
      IconData(0xf190, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData eye_16 =
      IconData(0xf191, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData eye_24 =
      IconData(0xf192, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData eye_closed_16 =
      IconData(0xf193, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData eye_closed_24 =
      IconData(0xf194, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData feed_discussion_16 =
      IconData(0xf195, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData feed_forked_16 =
      IconData(0xf196, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData feed_heart_16 =
      IconData(0xf197, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData feed_merged_16 =
      IconData(0xf198, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData feed_person_16 =
      IconData(0xf199, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData feed_repo_16 =
      IconData(0xf19a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData feed_rocket_16 =
      IconData(0xf19b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData feed_star_16 =
      IconData(0xf19c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData feed_tag_16 =
      IconData(0xf19d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData feed_trophy_16 =
      IconData(0xf19e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_16 =
      IconData(0xf19f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_24 =
      IconData(0xf1a0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_badge_16 =
      IconData(0xf1a1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_binary_16 =
      IconData(0xf1a2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_binary_24 =
      IconData(0xf1a3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_code_16 =
      IconData(0xf1a4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_code_24 =
      IconData(0xf1a5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_diff_16 =
      IconData(0xf1a6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_diff_24 =
      IconData(0xf1a7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_directory_16 =
      IconData(0xf1a8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_directory_24 =
      IconData(0xf1a9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_directory_fill_16 =
      IconData(0xf1aa, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_directory_fill_24 =
      IconData(0xf1ab, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_directory_open_fill_16 =
      IconData(0xf1ac, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_media_24 =
      IconData(0xf1ad, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_submodule_16 =
      IconData(0xf1ae, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_submodule_24 =
      IconData(0xf1af, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_symlink_file_16 =
      IconData(0xf1b0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_symlink_file_24 =
      IconData(0xf1b1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_zip_16 =
      IconData(0xf1b2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData file_zip_24 =
      IconData(0xf1b3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData filter_16 =
      IconData(0xf1b4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData filter_24 =
      IconData(0xf1b5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData flame_16 =
      IconData(0xf1b6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData flame_24 =
      IconData(0xf1b7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData fold_16 =
      IconData(0xf1b8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData fold_24 =
      IconData(0xf1b9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData fold_down_16 =
      IconData(0xf1ba, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData fold_down_24 =
      IconData(0xf1bb, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData fold_up_16 =
      IconData(0xf1bc, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData fold_up_24 =
      IconData(0xf1bd, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData gear_16 =
      IconData(0xf1be, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData gear_24 =
      IconData(0xf1bf, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData gift_16 =
      IconData(0xf1c0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData gift_24 =
      IconData(0xf1c1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData git_branch_16 =
      IconData(0xf1c2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData git_branch_24 =
      IconData(0xf1c3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData git_commit_16 =
      IconData(0xf1c4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData git_commit_24 =
      IconData(0xf1c5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData git_compare_16 =
      IconData(0xf1c6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData git_compare_24 =
      IconData(0xf1c7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData git_merge_16 =
      IconData(0xf1c8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData git_merge_24 =
      IconData(0xf1c9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData git_pull_request_16 =
      IconData(0xf1ca, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData git_pull_request_24 =
      IconData(0xf1cb, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData git_pull_request_closed_16 =
      IconData(0xf1cc, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData git_pull_request_closed_24 =
      IconData(0xf1cd, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData git_pull_request_draft_16 =
      IconData(0xf1ce, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData git_pull_request_draft_24 =
      IconData(0xf1cf, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData globe_16 =
      IconData(0xf1d0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData globe_24 =
      IconData(0xf1d1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData grabber_16 =
      IconData(0xf1d2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData grabber_24 =
      IconData(0xf1d3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData graph_16 =
      IconData(0xf1d4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData graph_24 =
      IconData(0xf1d5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData hash_16 =
      IconData(0xf1d6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData hash_24 =
      IconData(0xf1d7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData heading_16 =
      IconData(0xf1d8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData heading_24 =
      IconData(0xf1d9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData heart_16 =
      IconData(0xf1da, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData heart_24 =
      IconData(0xf1db, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData heart_fill_16 =
      IconData(0xf1dc, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData heart_fill_24 =
      IconData(0xf1dd, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData history_16 =
      IconData(0xf1de, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData history_24 =
      IconData(0xf1df, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData home_16 =
      IconData(0xf1e0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData home_24 =
      IconData(0xf1e1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData home_fill_24 =
      IconData(0xf1e2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData horizontal_rule_16 =
      IconData(0xf1e3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData horizontal_rule_24 =
      IconData(0xf1e4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData hourglass_16 =
      IconData(0xf1e5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData hourglass_24 =
      IconData(0xf1e6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData hubot_16 =
      IconData(0xf1e7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData hubot_24 =
      IconData(0xf1e8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData id_badge_16 =
      IconData(0xf1e9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData image_16 =
      IconData(0xf1ea, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData image_24 =
      IconData(0xf1eb, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData inbox_16 =
      IconData(0xf1ec, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData inbox_24 =
      IconData(0xf1ed, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData infinity_16 =
      IconData(0xf1ee, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData infinity_24 =
      IconData(0xf1ef, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData info_16 =
      IconData(0xf1f0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData info_24 =
      IconData(0xf1f1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData issue_closed_16 =
      IconData(0xf1f2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData issue_draft_16 =
      IconData(0xf1f4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData issue_draft_24 =
      IconData(0xf1f5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData issue_opened_16 =
      IconData(0xf1f6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData issue_opened_24 =
      IconData(0xf1f7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData issue_reopened_16 =
      IconData(0xf1f8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData issue_reopened_24 =
      IconData(0xf1f9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData italic_16 =
      IconData(0xf1fa, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData italic_24 =
      IconData(0xf1fb, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData iterations_16 =
      IconData(0xf1fc, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData iterations_24 =
      IconData(0xf1fd, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData kebab_horizontal_16 =
      IconData(0xf1fe, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData kebab_horizontal_24 =
      IconData(0xf1ff, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData key_16 =
      IconData(0xf200, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData key_24 =
      IconData(0xf201, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData key_asterisk_16 =
      IconData(0xf202, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData law_16 =
      IconData(0xf203, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData law_24 =
      IconData(0xf204, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData light_bulb_16 =
      IconData(0xf205, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData light_bulb_24 =
      IconData(0xf206, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData link_16 =
      IconData(0xf207, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData link_24 =
      IconData(0xf208, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData link_external_16 =
      IconData(0xf209, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData link_external_24 =
      IconData(0xf20a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData list_ordered_16 =
      IconData(0xf20b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData list_ordered_24 =
      IconData(0xf20c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData list_unordered_16 =
      IconData(0xf20d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData list_unordered_24 =
      IconData(0xf20e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData location_16 =
      IconData(0xf20f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData location_24 =
      IconData(0xf210, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData lock_16 =
      IconData(0xf211, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData lock_24 =
      IconData(0xf212, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData log_16 =
      IconData(0xf213, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData logo_gist_16 =
      IconData(0xf214, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData logo_github_16 =
      IconData(0xf215, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData mail_16 =
      IconData(0xf216, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData mail_24 =
      IconData(0xf217, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData mark_github_16 =
      IconData(0xf218, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData markdown_16 =
      IconData(0xf219, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData megaphone_16 =
      IconData(0xf21a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData megaphone_24 =
      IconData(0xf21b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData mention_16 =
      IconData(0xf21c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData mention_24 =
      IconData(0xf21d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData meter_16 =
      IconData(0xf21e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData milestone_16 =
      IconData(0xf21f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData milestone_24 =
      IconData(0xf220, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData mirror_16 =
      IconData(0xf221, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData mirror_24 =
      IconData(0xf222, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData moon_16 =
      IconData(0xf223, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData moon_24 =
      IconData(0xf224, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData mortar_board_16 =
      IconData(0xf225, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData mortar_board_24 =
      IconData(0xf226, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData multi_select_16 =
      IconData(0xf227, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData multi_select_24 =
      IconData(0xf228, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData mute_16 =
      IconData(0xf229, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData mute_24 =
      IconData(0xf22a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData no_entry_16 =
      IconData(0xf22b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData no_entry_24 =
      IconData(0xf22c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData no_entry_fill_12 =
      IconData(0xf22d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData north_star_16 =
      IconData(0xf22e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData north_star_24 =
      IconData(0xf22f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData note_16 =
      IconData(0xf230, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData note_24 =
      IconData(0xf231, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData number_16 =
      IconData(0xf232, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData number_24 =
      IconData(0xf233, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData organization_16 =
      IconData(0xf234, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData organization_24 =
      IconData(0xf235, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData package_16 =
      IconData(0xf236, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData package_24 =
      IconData(0xf237, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData package_dependencies_16 =
      IconData(0xf238, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData package_dependencies_24 =
      IconData(0xf239, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData package_dependents_16 =
      IconData(0xf23a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData package_dependents_24 =
      IconData(0xf23b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData paintbrush_16 =
      IconData(0xf23c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData paper_airplane_16 =
      IconData(0xf23d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData paper_airplane_24 =
      IconData(0xf23e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData paste_16 =
      IconData(0xf23f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData paste_24 =
      IconData(0xf240, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData pencil_16 =
      IconData(0xf241, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData pencil_24 =
      IconData(0xf242, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData people_16 =
      IconData(0xf243, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData people_24 =
      IconData(0xf244, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData person_16 =
      IconData(0xf245, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData person_24 =
      IconData(0xf246, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData person_add_16 =
      IconData(0xf247, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData person_add_24 =
      IconData(0xf248, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData person_fill_16 =
      IconData(0xf249, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData person_fill_24 =
      IconData(0xf24a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData pin_16 =
      IconData(0xf24b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData pin_24 =
      IconData(0xf24c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData play_16 =
      IconData(0xf24d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData play_24 =
      IconData(0xf24e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData plug_16 =
      IconData(0xf24f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData plug_24 =
      IconData(0xf250, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData plus_16 =
      IconData(0xf251, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData plus_24 =
      IconData(0xf252, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData plus_circle_16 =
      IconData(0xf253, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData plus_circle_24 =
      IconData(0xf254, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData project_16 =
      IconData(0xf255, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData project_24 =
      IconData(0xf256, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData pulse_16 =
      IconData(0xf257, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData pulse_24 =
      IconData(0xf258, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData question_16 =
      IconData(0xf259, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData question_24 =
      IconData(0xf25a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData quote_16 =
      IconData(0xf25b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData quote_24 =
      IconData(0xf25c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData reply_16 =
      IconData(0xf25d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData reply_24 =
      IconData(0xf25e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData repo_16 =
      IconData(0xf25f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData repo_24 =
      IconData(0xf260, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData repo_clone_16 =
      IconData(0xf261, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData repo_deleted_16 =
      IconData(0xf262, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData repo_forked_16 =
      IconData(0xf263, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData repo_forked_24 =
      IconData(0xf264, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData repo_locked_16 =
      IconData(0xf265, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData repo_pull_16 =
      IconData(0xf266, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData repo_push_16 =
      IconData(0xf267, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData repo_push_24 =
      IconData(0xf268, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData repo_template_16 =
      IconData(0xf269, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData repo_template_24 =
      IconData(0xf26a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData report_16 =
      IconData(0xf26b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData report_24 =
      IconData(0xf26c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData rocket_16 =
      IconData(0xf26d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData rocket_24 =
      IconData(0xf26e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData rows_16 =
      IconData(0xf26f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData rows_24 =
      IconData(0xf270, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData rss_16 =
      IconData(0xf271, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData rss_24 =
      IconData(0xf272, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData ruby_16 =
      IconData(0xf273, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData ruby_24 =
      IconData(0xf274, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData screen_full_16 =
      IconData(0xf275, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData screen_full_24 =
      IconData(0xf276, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData screen_normal_16 =
      IconData(0xf277, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData screen_normal_24 =
      IconData(0xf278, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData search_16 =
      IconData(0xf279, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData search_24 =
      IconData(0xf27a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData server_16 =
      IconData(0xf27b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData server_24 =
      IconData(0xf27c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData share_16 =
      IconData(0xf27d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData share_24 =
      IconData(0xf27e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData share_android_16 =
      IconData(0xf27f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData share_android_24 =
      IconData(0xf280, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData shield_16 =
      IconData(0xf281, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData shield_24 =
      IconData(0xf282, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData shield_check_16 =
      IconData(0xf283, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData shield_check_24 =
      IconData(0xf284, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData shield_lock_16 =
      IconData(0xf285, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData shield_lock_24 =
      IconData(0xf286, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData shield_x_16 =
      IconData(0xf287, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData shield_x_24 =
      IconData(0xf288, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sidebar_collapse_16 =
      IconData(0xf289, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sidebar_collapse_24 =
      IconData(0xf28a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sidebar_expand_16 =
      IconData(0xf28b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sidebar_expand_24 =
      IconData(0xf28c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sign_in_16 =
      IconData(0xf28d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sign_in_24 =
      IconData(0xf28e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sign_out_16 =
      IconData(0xf28f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sign_out_24 =
      IconData(0xf290, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData single_select_16 =
      IconData(0xf291, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData single_select_24 =
      IconData(0xf292, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData skip_16 =
      IconData(0xf293, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData skip_24 =
      IconData(0xf294, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sliders_16 =
      IconData(0xf295, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData smiley_16 =
      IconData(0xf296, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData smiley_24 =
      IconData(0xf297, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sort_asc_16 =
      IconData(0xf298, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sort_asc_24 =
      IconData(0xf299, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sort_desc_16 =
      IconData(0xf29a, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sort_desc_24 =
      IconData(0xf29b, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData square_16 =
      IconData(0xf29c, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData square_24 =
      IconData(0xf29d, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData square_fill_16 =
      IconData(0xf29e, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData square_fill_24 =
      IconData(0xf29f, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData squirrel_16 =
      IconData(0xf2a0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData squirrel_24 =
      IconData(0xf2a1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData stack_16 =
      IconData(0xf2a2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData stack_24 =
      IconData(0xf2a3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData star_16 =
      IconData(0xf2a4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData star_24 =
      IconData(0xf2a5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData star_fill_16 =
      IconData(0xf2a6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData star_fill_24 =
      IconData(0xf2a7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData stop_16 =
      IconData(0xf2a8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData stop_24 =
      IconData(0xf2a9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData stopwatch_16 =
      IconData(0xf2aa, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData stopwatch_24 =
      IconData(0xf2ab, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData strikethrough_16 =
      IconData(0xf2ac, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData strikethrough_24 =
      IconData(0xf2ad, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sun_16 =
      IconData(0xf2ae, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sun_24 =
      IconData(0xf2af, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sync_16 =
      IconData(0xf2b0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData sync_24 =
      IconData(0xf2b1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData tab_24 =
      IconData(0xf2b2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData tab_external_16 =
      IconData(0xf2b3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData table_16 =
      IconData(0xf2b4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData table_24 =
      IconData(0xf2b5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData tag_16 =
      IconData(0xf2b6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData tag_24 =
      IconData(0xf2b7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData tasklist_16 =
      IconData(0xf2b8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData tasklist_24 =
      IconData(0xf2b9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData telescope_16 =
      IconData(0xf2ba, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData telescope_24 =
      IconData(0xf2bb, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData telescope_fill_16 =
      IconData(0xf2bc, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData telescope_fill_24 =
      IconData(0xf2bd, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData terminal_16 =
      IconData(0xf2be, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData terminal_24 =
      IconData(0xf2bf, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData three_bars_16 =
      IconData(0xf2c0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData thumbsdown_16 =
      IconData(0xf2c1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData thumbsdown_24 =
      IconData(0xf2c2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData thumbsup_16 =
      IconData(0xf2c3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData thumbsup_24 =
      IconData(0xf2c4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData tools_16 =
      IconData(0xf2c5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData tools_24 =
      IconData(0xf2c6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData trash_16 =
      IconData(0xf2c7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData trash_24 =
      IconData(0xf2c8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData triangle_down_16 =
      IconData(0xf2c9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData triangle_down_24 =
      IconData(0xf2ca, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData triangle_left_16 =
      IconData(0xf2cb, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData triangle_left_24 =
      IconData(0xf2cc, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData triangle_right_16 =
      IconData(0xf2cd, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData triangle_right_24 =
      IconData(0xf2ce, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData triangle_up_16 =
      IconData(0xf2cf, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData triangle_up_24 =
      IconData(0xf2d0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData trophy_16 =
      IconData(0xf2d1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData trophy_24 =
      IconData(0xf2d2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData typography_16 =
      IconData(0xf2d3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData typography_24 =
      IconData(0xf2d4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData unfold_16 =
      IconData(0xf2d5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData unfold_24 =
      IconData(0xf2d6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData unlock_16 =
      IconData(0xf2d7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData unlock_24 =
      IconData(0xf2d8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData unmute_16 =
      IconData(0xf2d9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData unmute_24 =
      IconData(0xf2da, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData unverified_16 =
      IconData(0xf2db, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData unverified_24 =
      IconData(0xf2dc, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData upload_16 =
      IconData(0xf2dd, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData upload_24 =
      IconData(0xf2de, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData verified_16 =
      IconData(0xf2df, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData verified_24 =
      IconData(0xf2e0, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData versions_16 =
      IconData(0xf2e1, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData versions_24 =
      IconData(0xf2e2, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData video_16 =
      IconData(0xf2e3, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData video_24 =
      IconData(0xf2e4, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData webhook_16 =
      IconData(0xf2e5, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData workflow_16 =
      IconData(0xf2e6, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData workflow_24 =
      IconData(0xf2e7, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData x_16 =
      IconData(0xf2e8, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData x_24 =
      IconData(0xf2e9, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData x_circle_16 =
      IconData(0xf2ea, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData x_circle_24 =
      IconData(0xf2eb, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData x_circle_fill_12 =
      IconData(0xf2ec, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData x_circle_fill_16 =
      IconData(0xf2ed, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData x_circle_fill_24 =
      IconData(0xf2ee, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData zap_16 =
      IconData(0xf2ef, fontFamily: _fontFamily, fontPackage: _fontPackage);
  static const IconData zap_24 =
      IconData(0xf2f0, fontFamily: _fontFamily, fontPackage: _fontPackage);
}
