import 'package:flutter_octicons/flutter_octicons.dart';
import 'package:flutter_octicons_example/icon_info.dart';

const List<IconInfo> octicons = [
  IconInfo(name: "accessibility-16", icon: OctIcons.accessibility_16, size: 16),
  IconInfo(name: "accessibility-24", icon: OctIcons.accessibility_24, size: 24),
  IconInfo(
      name: "accessibility-inset-16",
      icon: OctIcons.accessibility_inset_16,
      size: 16),
  IconInfo(
      name: "accessibility-inset-24",
      icon: OctIcons.accessibility_inset_24,
      size: 24),
  IconInfo(name: "ai-model-16", icon: OctIcons.ai_model_16, size: 16),
  IconInfo(name: "ai-model-24", icon: OctIcons.ai_model_24, size: 24),
  IconInfo(name: "alert-16", icon: OctIcons.alert_16, size: 16),
  IconInfo(name: "alert-24", icon: OctIcons.alert_24, size: 24),
  IconInfo(name: "alert-fill-12", icon: OctIcons.alert_fill_12, size: 12),
  IconInfo(name: "alert-fill-16", icon: OctIcons.alert_fill_16, size: 16),
  IconInfo(name: "alert-fill-24", icon: OctIcons.alert_fill_24, size: 24),
  IconInfo(name: "apps-16", icon: OctIcons.apps_16, size: 16),
  IconInfo(name: "apps-24", icon: OctIcons.apps_24, size: 24),
  IconInfo(name: "archive-16", icon: OctIcons.archive_16, size: 16),
  IconInfo(name: "archive-24", icon: OctIcons.archive_24, size: 24),
  IconInfo(name: "arrow-both-16", icon: OctIcons.arrow_both_16, size: 16),
  IconInfo(name: "arrow-both-24", icon: OctIcons.arrow_both_24, size: 24),
  IconInfo(name: "arrow-down-16", icon: OctIcons.arrow_down_16, size: 16),
  IconInfo(name: "arrow-down-24", icon: OctIcons.arrow_down_24, size: 24),
  IconInfo(
      name: "arrow-down-left-16", icon: OctIcons.arrow_down_left_16, size: 16),
  IconInfo(
      name: "arrow-down-left-24", icon: OctIcons.arrow_down_left_24, size: 24),
  IconInfo(
      name: "arrow-down-right-16",
      icon: OctIcons.arrow_down_right_16,
      size: 16),
  IconInfo(
      name: "arrow-down-right-24",
      icon: OctIcons.arrow_down_right_24,
      size: 24),
  IconInfo(name: "arrow-left-16", icon: OctIcons.arrow_left_16, size: 16),
  IconInfo(name: "arrow-left-24", icon: OctIcons.arrow_left_24, size: 24),
  IconInfo(name: "arrow-right-16", icon: OctIcons.arrow_right_16, size: 16),
  IconInfo(name: "arrow-right-24", icon: OctIcons.arrow_right_24, size: 24),
  IconInfo(name: "arrow-switch-16", icon: OctIcons.arrow_switch_16, size: 16),
  IconInfo(name: "arrow-switch-24", icon: OctIcons.arrow_switch_24, size: 24),
  IconInfo(name: "arrow-up-16", icon: OctIcons.arrow_up_16, size: 16),
  IconInfo(name: "arrow-up-24", icon: OctIcons.arrow_up_24, size: 24),
  IconInfo(name: "arrow-up-left-16", icon: OctIcons.arrow_up_left_16, size: 16),
  IconInfo(name: "arrow-up-left-24", icon: OctIcons.arrow_up_left_24, size: 24),
  IconInfo(
      name: "arrow-up-right-16", icon: OctIcons.arrow_up_right_16, size: 16),
  IconInfo(
      name: "arrow-up-right-24", icon: OctIcons.arrow_up_right_24, size: 24),
  IconInfo(name: "beaker-16", icon: OctIcons.beaker_16, size: 16),
  IconInfo(name: "beaker-24", icon: OctIcons.beaker_24, size: 24),
  IconInfo(name: "bell-16", icon: OctIcons.bell_16, size: 16),
  IconInfo(name: "bell-24", icon: OctIcons.bell_24, size: 24),
  IconInfo(name: "bell-fill-16", icon: OctIcons.bell_fill_16, size: 16),
  IconInfo(name: "bell-fill-24", icon: OctIcons.bell_fill_24, size: 24),
  IconInfo(name: "bell-slash-16", icon: OctIcons.bell_slash_16, size: 16),
  IconInfo(name: "bell-slash-24", icon: OctIcons.bell_slash_24, size: 24),
  IconInfo(name: "blocked-16", icon: OctIcons.blocked_16, size: 16),
  IconInfo(name: "blocked-24", icon: OctIcons.blocked_24, size: 24),
  IconInfo(name: "bold-16", icon: OctIcons.bold_16, size: 16),
  IconInfo(name: "bold-24", icon: OctIcons.bold_24, size: 24),
  IconInfo(name: "book-16", icon: OctIcons.book_16, size: 16),
  IconInfo(name: "book-24", icon: OctIcons.book_24, size: 24),
  IconInfo(name: "bookmark-16", icon: OctIcons.bookmark_16, size: 16),
  IconInfo(name: "bookmark-24", icon: OctIcons.bookmark_24, size: 24),
  IconInfo(name: "bookmark-fill-24", icon: OctIcons.bookmark_fill_24, size: 24),
  IconInfo(
      name: "bookmark-filled-16", icon: OctIcons.bookmark_filled_16, size: 16),
  IconInfo(
      name: "bookmark-slash-16", icon: OctIcons.bookmark_slash_16, size: 16),
  IconInfo(
      name: "bookmark-slash-24", icon: OctIcons.bookmark_slash_24, size: 24),
  IconInfo(
      name: "bookmark-slash-fill-16",
      icon: OctIcons.bookmark_slash_fill_16,
      size: 16),
  IconInfo(
      name: "bookmark-slash-fill-24",
      icon: OctIcons.bookmark_slash_fill_24,
      size: 24),
  IconInfo(name: "briefcase-16", icon: OctIcons.briefcase_16, size: 16),
  IconInfo(name: "briefcase-24", icon: OctIcons.briefcase_24, size: 24),
  IconInfo(name: "broadcast-16", icon: OctIcons.broadcast_16, size: 16),
  IconInfo(name: "broadcast-24", icon: OctIcons.broadcast_24, size: 24),
  IconInfo(name: "browser-16", icon: OctIcons.browser_16, size: 16),
  IconInfo(name: "browser-24", icon: OctIcons.browser_24, size: 24),
  IconInfo(name: "bug-16", icon: OctIcons.bug_16, size: 16),
  IconInfo(name: "bug-24", icon: OctIcons.bug_24, size: 24),
  IconInfo(name: "cache-16", icon: OctIcons.cache_16, size: 16),
  IconInfo(name: "cache-24", icon: OctIcons.cache_24, size: 24),
  IconInfo(name: "calendar-16", icon: OctIcons.calendar_16, size: 16),
  IconInfo(name: "calendar-24", icon: OctIcons.calendar_24, size: 24),
  IconInfo(name: "check-16", icon: OctIcons.check_16, size: 16),
  IconInfo(name: "check-24", icon: OctIcons.check_24, size: 24),
  IconInfo(name: "check-circle-16", icon: OctIcons.check_circle_16, size: 16),
  IconInfo(name: "check-circle-24", icon: OctIcons.check_circle_24, size: 24),
  IconInfo(
      name: "check-circle-fill-12",
      icon: OctIcons.check_circle_fill_12,
      size: 12),
  IconInfo(
      name: "check-circle-fill-16",
      icon: OctIcons.check_circle_fill_16,
      size: 16),
  IconInfo(
      name: "check-circle-fill-24",
      icon: OctIcons.check_circle_fill_24,
      size: 24),
  IconInfo(name: "checkbox-16", icon: OctIcons.checkbox_16, size: 16),
  IconInfo(name: "checkbox-24", icon: OctIcons.checkbox_24, size: 24),
  IconInfo(name: "checklist-16", icon: OctIcons.checklist_16, size: 16),
  IconInfo(name: "checklist-24", icon: OctIcons.checklist_24, size: 24),
  IconInfo(name: "chevron-down-12", icon: OctIcons.chevron_down_12, size: 12),
  IconInfo(name: "chevron-down-16", icon: OctIcons.chevron_down_16, size: 16),
  IconInfo(name: "chevron-down-24", icon: OctIcons.chevron_down_24, size: 24),
  IconInfo(name: "chevron-left-12", icon: OctIcons.chevron_left_12, size: 12),
  IconInfo(name: "chevron-left-16", icon: OctIcons.chevron_left_16, size: 16),
  IconInfo(name: "chevron-left-24", icon: OctIcons.chevron_left_24, size: 24),
  IconInfo(name: "chevron-right-12", icon: OctIcons.chevron_right_12, size: 12),
  IconInfo(name: "chevron-right-16", icon: OctIcons.chevron_right_16, size: 16),
  IconInfo(name: "chevron-right-24", icon: OctIcons.chevron_right_24, size: 24),
  IconInfo(name: "chevron-up-12", icon: OctIcons.chevron_up_12, size: 12),
  IconInfo(name: "chevron-up-16", icon: OctIcons.chevron_up_16, size: 16),
  IconInfo(name: "chevron-up-24", icon: OctIcons.chevron_up_24, size: 24),
  IconInfo(name: "circle-16", icon: OctIcons.circle_16, size: 16),
  IconInfo(name: "circle-24", icon: OctIcons.circle_24, size: 24),
  IconInfo(name: "circle-slash-16", icon: OctIcons.circle_slash_16, size: 16),
  IconInfo(name: "circle-slash-24", icon: OctIcons.circle_slash_24, size: 24),
  IconInfo(name: "clock-16", icon: OctIcons.clock_16, size: 16),
  IconInfo(name: "clock-24", icon: OctIcons.clock_24, size: 24),
  IconInfo(name: "clock-fill-16", icon: OctIcons.clock_fill_16, size: 16),
  IconInfo(name: "clock-fill-24", icon: OctIcons.clock_fill_24, size: 24),
  IconInfo(name: "cloud-16", icon: OctIcons.cloud_16, size: 16),
  IconInfo(name: "cloud-24", icon: OctIcons.cloud_24, size: 24),
  IconInfo(name: "cloud-offline-16", icon: OctIcons.cloud_offline_16, size: 16),
  IconInfo(name: "cloud-offline-24", icon: OctIcons.cloud_offline_24, size: 24),
  IconInfo(name: "code-16", icon: OctIcons.code_16, size: 16),
  IconInfo(name: "code-24", icon: OctIcons.code_24, size: 24),
  IconInfo(
      name: "code-of-conduct-16", icon: OctIcons.code_of_conduct_16, size: 16),
  IconInfo(
      name: "code-of-conduct-24", icon: OctIcons.code_of_conduct_24, size: 24),
  IconInfo(name: "code-review-16", icon: OctIcons.code_review_16, size: 16),
  IconInfo(name: "code-review-24", icon: OctIcons.code_review_24, size: 24),
  IconInfo(name: "code-square-16", icon: OctIcons.code_square_16, size: 16),
  IconInfo(name: "code-square-24", icon: OctIcons.code_square_24, size: 24),
  IconInfo(name: "codescan-16", icon: OctIcons.codescan_16, size: 16),
  IconInfo(name: "codescan-24", icon: OctIcons.codescan_24, size: 24),
  IconInfo(
      name: "codescan-checkmark-16",
      icon: OctIcons.codescan_checkmark_16,
      size: 16),
  IconInfo(
      name: "codescan-checkmark-24",
      icon: OctIcons.codescan_checkmark_24,
      size: 24),
  IconInfo(name: "codespaces-16", icon: OctIcons.codespaces_16, size: 16),
  IconInfo(name: "codespaces-24", icon: OctIcons.codespaces_24, size: 24),
  IconInfo(name: "columns-16", icon: OctIcons.columns_16, size: 16),
  IconInfo(name: "columns-24", icon: OctIcons.columns_24, size: 24),
  IconInfo(
      name: "command-palette-16", icon: OctIcons.command_palette_16, size: 16),
  IconInfo(
      name: "command-palette-24", icon: OctIcons.command_palette_24, size: 24),
  IconInfo(name: "comment-16", icon: OctIcons.comment_16, size: 16),
  IconInfo(name: "comment-24", icon: OctIcons.comment_24, size: 24),
  IconInfo(
      name: "comment-discussion-16",
      icon: OctIcons.comment_discussion_16,
      size: 16),
  IconInfo(
      name: "comment-discussion-24",
      icon: OctIcons.comment_discussion_24,
      size: 24),
  IconInfo(name: "container-16", icon: OctIcons.container_16, size: 16),
  IconInfo(name: "container-24", icon: OctIcons.container_24, size: 24),
  IconInfo(name: "copilot-16", icon: OctIcons.copilot_16, size: 16),
  IconInfo(name: "copilot-24", icon: OctIcons.copilot_24, size: 24),
  IconInfo(name: "copilot-48", icon: OctIcons.copilot_48, size: 48),
  IconInfo(name: "copilot-96", icon: OctIcons.copilot_96, size: 96),
  IconInfo(name: "copilot-error-16", icon: OctIcons.copilot_error_16, size: 16),
  IconInfo(
      name: "copilot-warning-16", icon: OctIcons.copilot_warning_16, size: 16),
  IconInfo(name: "copy-16", icon: OctIcons.copy_16, size: 16),
  IconInfo(name: "copy-24", icon: OctIcons.copy_24, size: 24),
  IconInfo(name: "cpu-16", icon: OctIcons.cpu_16, size: 16),
  IconInfo(name: "cpu-24", icon: OctIcons.cpu_24, size: 24),
  IconInfo(name: "credit-card-16", icon: OctIcons.credit_card_16, size: 16),
  IconInfo(name: "credit-card-24", icon: OctIcons.credit_card_24, size: 24),
  IconInfo(
      name: "cross-reference-16", icon: OctIcons.cross_reference_16, size: 16),
  IconInfo(
      name: "cross-reference-24", icon: OctIcons.cross_reference_24, size: 24),
  IconInfo(name: "dash-16", icon: OctIcons.dash_16, size: 16),
  IconInfo(name: "dash-24", icon: OctIcons.dash_24, size: 24),
  IconInfo(name: "database-16", icon: OctIcons.database_16, size: 16),
  IconInfo(name: "database-24", icon: OctIcons.database_24, size: 24),
  IconInfo(name: "dependabot-16", icon: OctIcons.dependabot_16, size: 16),
  IconInfo(name: "dependabot-24", icon: OctIcons.dependabot_24, size: 24),
  IconInfo(
      name: "desktop-download-16",
      icon: OctIcons.desktop_download_16,
      size: 16),
  IconInfo(
      name: "desktop-download-24",
      icon: OctIcons.desktop_download_24,
      size: 24),
  IconInfo(name: "device-camera-16", icon: OctIcons.device_camera_16, size: 16),
  IconInfo(name: "device-camera-24", icon: OctIcons.device_camera_24, size: 24),
  IconInfo(
      name: "device-camera-video-16",
      icon: OctIcons.device_camera_video_16,
      size: 16),
  IconInfo(
      name: "device-camera-video-24",
      icon: OctIcons.device_camera_video_24,
      size: 24),
  IconInfo(
      name: "device-desktop-16", icon: OctIcons.device_desktop_16, size: 16),
  IconInfo(
      name: "device-desktop-24", icon: OctIcons.device_desktop_24, size: 24),
  IconInfo(name: "device-mobile-16", icon: OctIcons.device_mobile_16, size: 16),
  IconInfo(name: "device-mobile-24", icon: OctIcons.device_mobile_24, size: 24),
  IconInfo(name: "devices-16", icon: OctIcons.devices_16, size: 16),
  IconInfo(name: "devices-24", icon: OctIcons.devices_24, size: 24),
  IconInfo(name: "diamond-16", icon: OctIcons.diamond_16, size: 16),
  IconInfo(name: "diamond-24", icon: OctIcons.diamond_24, size: 24),
  IconInfo(name: "diff-16", icon: OctIcons.diff_16, size: 16),
  IconInfo(name: "diff-24", icon: OctIcons.diff_24, size: 24),
  IconInfo(name: "diff-added-16", icon: OctIcons.diff_added_16, size: 16),
  IconInfo(name: "diff-added-24", icon: OctIcons.diff_added_24, size: 24),
  IconInfo(name: "diff-ignored-16", icon: OctIcons.diff_ignored_16, size: 16),
  IconInfo(name: "diff-ignored-24", icon: OctIcons.diff_ignored_24, size: 24),
  IconInfo(name: "diff-modified-16", icon: OctIcons.diff_modified_16, size: 16),
  IconInfo(name: "diff-modified-24", icon: OctIcons.diff_modified_24, size: 24),
  IconInfo(name: "diff-removed-16", icon: OctIcons.diff_removed_16, size: 16),
  IconInfo(name: "diff-removed-24", icon: OctIcons.diff_removed_24, size: 24),
  IconInfo(name: "diff-renamed-16", icon: OctIcons.diff_renamed_16, size: 16),
  IconInfo(name: "diff-renamed-24", icon: OctIcons.diff_renamed_24, size: 24),
  IconInfo(
      name: "discussion-closed-16",
      icon: OctIcons.discussion_closed_16,
      size: 16),
  IconInfo(
      name: "discussion-closed-24",
      icon: OctIcons.discussion_closed_24,
      size: 24),
  IconInfo(
      name: "discussion-duplicate-16",
      icon: OctIcons.discussion_duplicate_16,
      size: 16),
  IconInfo(
      name: "discussion-duplicate-24",
      icon: OctIcons.discussion_duplicate_24,
      size: 24),
  IconInfo(
      name: "discussion-outdated-16",
      icon: OctIcons.discussion_outdated_16,
      size: 16),
  IconInfo(
      name: "discussion-outdated-24",
      icon: OctIcons.discussion_outdated_24,
      size: 24),
  IconInfo(name: "dot-16", icon: OctIcons.dot_16, size: 16),
  IconInfo(name: "dot-24", icon: OctIcons.dot_24, size: 24),
  IconInfo(name: "dot-fill-16", icon: OctIcons.dot_fill_16, size: 16),
  IconInfo(name: "dot-fill-24", icon: OctIcons.dot_fill_24, size: 24),
  IconInfo(name: "download-16", icon: OctIcons.download_16, size: 16),
  IconInfo(name: "download-24", icon: OctIcons.download_24, size: 24),
  IconInfo(name: "duplicate-16", icon: OctIcons.duplicate_16, size: 16),
  IconInfo(name: "duplicate-24", icon: OctIcons.duplicate_24, size: 24),
  IconInfo(name: "ellipsis-16", icon: OctIcons.ellipsis_16, size: 16),
  IconInfo(name: "ellipsis-24", icon: OctIcons.ellipsis_24, size: 24),
  IconInfo(name: "eye-16", icon: OctIcons.eye_16, size: 16),
  IconInfo(name: "eye-24", icon: OctIcons.eye_24, size: 24),
  IconInfo(name: "eye-closed-16", icon: OctIcons.eye_closed_16, size: 16),
  IconInfo(name: "eye-closed-24", icon: OctIcons.eye_closed_24, size: 24),
  IconInfo(
      name: "feed-discussion-16", icon: OctIcons.feed_discussion_16, size: 16),
  IconInfo(name: "feed-forked-16", icon: OctIcons.feed_forked_16, size: 16),
  IconInfo(name: "feed-heart-16", icon: OctIcons.feed_heart_16, size: 16),
  IconInfo(
      name: "feed-issue-closed-16",
      icon: OctIcons.feed_issue_closed_16,
      size: 16),
  IconInfo(
      name: "feed-issue-draft-16",
      icon: OctIcons.feed_issue_draft_16,
      size: 16),
  IconInfo(
      name: "feed-issue-open-16", icon: OctIcons.feed_issue_open_16, size: 16),
  IconInfo(
      name: "feed-issue-reopen-16",
      icon: OctIcons.feed_issue_reopen_16,
      size: 16),
  IconInfo(name: "feed-merged-16", icon: OctIcons.feed_merged_16, size: 16),
  IconInfo(name: "feed-person-16", icon: OctIcons.feed_person_16, size: 16),
  IconInfo(name: "feed-plus-16", icon: OctIcons.feed_plus_16, size: 16),
  IconInfo(name: "feed-public-16", icon: OctIcons.feed_public_16, size: 16),
  IconInfo(
      name: "feed-pull-request-closed-16",
      icon: OctIcons.feed_pull_request_closed_16,
      size: 16),
  IconInfo(
      name: "feed-pull-request-draft-16",
      icon: OctIcons.feed_pull_request_draft_16,
      size: 16),
  IconInfo(
      name: "feed-pull-request-open-16",
      icon: OctIcons.feed_pull_request_open_16,
      size: 16),
  IconInfo(name: "feed-repo-16", icon: OctIcons.feed_repo_16, size: 16),
  IconInfo(name: "feed-rocket-16", icon: OctIcons.feed_rocket_16, size: 16),
  IconInfo(name: "feed-star-16", icon: OctIcons.feed_star_16, size: 16),
  IconInfo(name: "feed-tag-16", icon: OctIcons.feed_tag_16, size: 16),
  IconInfo(name: "feed-trophy-16", icon: OctIcons.feed_trophy_16, size: 16),
  IconInfo(name: "file-16", icon: OctIcons.file_16, size: 16),
  IconInfo(name: "file-24", icon: OctIcons.file_24, size: 24),
  IconInfo(name: "file-added-16", icon: OctIcons.file_added_16, size: 16),
  IconInfo(name: "file-added-24", icon: OctIcons.file_added_24, size: 24),
  IconInfo(name: "file-badge-16", icon: OctIcons.file_badge_16, size: 16),
  IconInfo(name: "file-badge-24", icon: OctIcons.file_badge_24, size: 24),
  IconInfo(name: "file-binary-16", icon: OctIcons.file_binary_16, size: 16),
  IconInfo(name: "file-binary-24", icon: OctIcons.file_binary_24, size: 24),
  IconInfo(name: "file-code-16", icon: OctIcons.file_code_16, size: 16),
  IconInfo(name: "file-code-24", icon: OctIcons.file_code_24, size: 24),
  IconInfo(name: "file-diff-16", icon: OctIcons.file_diff_16, size: 16),
  IconInfo(name: "file-diff-24", icon: OctIcons.file_diff_24, size: 24),
  IconInfo(
      name: "file-directory-16", icon: OctIcons.file_directory_16, size: 16),
  IconInfo(
      name: "file-directory-24", icon: OctIcons.file_directory_24, size: 24),
  IconInfo(
      name: "file-directory-fill-16",
      icon: OctIcons.file_directory_fill_16,
      size: 16),
  IconInfo(
      name: "file-directory-fill-24",
      icon: OctIcons.file_directory_fill_24,
      size: 24),
  IconInfo(
      name: "file-directory-open-fill-16",
      icon: OctIcons.file_directory_open_fill_16,
      size: 16),
  IconInfo(
      name: "file-directory-open-fill-24",
      icon: OctIcons.file_directory_open_fill_24,
      size: 24),
  IconInfo(
      name: "file-directory-symlink-16",
      icon: OctIcons.file_directory_symlink_16,
      size: 16),
  IconInfo(
      name: "file-directory-symlink-24",
      icon: OctIcons.file_directory_symlink_24,
      size: 24),
  IconInfo(name: "file-media-16", icon: OctIcons.file_media_16, size: 16),
  IconInfo(name: "file-media-24", icon: OctIcons.file_media_24, size: 24),
  IconInfo(name: "file-moved-16", icon: OctIcons.file_moved_16, size: 16),
  IconInfo(name: "file-moved-24", icon: OctIcons.file_moved_24, size: 24),
  IconInfo(name: "file-removed-16", icon: OctIcons.file_removed_16, size: 16),
  IconInfo(name: "file-removed-24", icon: OctIcons.file_removed_24, size: 24),
  IconInfo(
      name: "file-submodule-16", icon: OctIcons.file_submodule_16, size: 16),
  IconInfo(
      name: "file-submodule-24", icon: OctIcons.file_submodule_24, size: 24),
  IconInfo(
      name: "file-symlink-file-16",
      icon: OctIcons.file_symlink_file_16,
      size: 16),
  IconInfo(
      name: "file-symlink-file-24",
      icon: OctIcons.file_symlink_file_24,
      size: 24),
  IconInfo(name: "file-zip-16", icon: OctIcons.file_zip_16, size: 16),
  IconInfo(name: "file-zip-24", icon: OctIcons.file_zip_24, size: 24),
  IconInfo(name: "filter-16", icon: OctIcons.filter_16, size: 16),
  IconInfo(name: "filter-24", icon: OctIcons.filter_24, size: 24),
  IconInfo(name: "filter-remove-16", icon: OctIcons.filter_remove_16, size: 16),
  IconInfo(name: "filter-remove-24", icon: OctIcons.filter_remove_24, size: 24),
  IconInfo(name: "fiscal-host-16", icon: OctIcons.fiscal_host_16, size: 16),
  IconInfo(name: "fiscal-host-24", icon: OctIcons.fiscal_host_24, size: 24),
  IconInfo(name: "flame-16", icon: OctIcons.flame_16, size: 16),
  IconInfo(name: "flame-24", icon: OctIcons.flame_24, size: 24),
  IconInfo(name: "fold-16", icon: OctIcons.fold_16, size: 16),
  IconInfo(name: "fold-24", icon: OctIcons.fold_24, size: 24),
  IconInfo(name: "fold-down-16", icon: OctIcons.fold_down_16, size: 16),
  IconInfo(name: "fold-down-24", icon: OctIcons.fold_down_24, size: 24),
  IconInfo(name: "fold-up-16", icon: OctIcons.fold_up_16, size: 16),
  IconInfo(name: "fold-up-24", icon: OctIcons.fold_up_24, size: 24),
  IconInfo(name: "gear-16", icon: OctIcons.gear_16, size: 16),
  IconInfo(name: "gear-24", icon: OctIcons.gear_24, size: 24),
  IconInfo(name: "gift-16", icon: OctIcons.gift_16, size: 16),
  IconInfo(name: "gift-24", icon: OctIcons.gift_24, size: 24),
  IconInfo(name: "git-branch-16", icon: OctIcons.git_branch_16, size: 16),
  IconInfo(name: "git-branch-24", icon: OctIcons.git_branch_24, size: 24),
  IconInfo(name: "git-commit-16", icon: OctIcons.git_commit_16, size: 16),
  IconInfo(name: "git-commit-24", icon: OctIcons.git_commit_24, size: 24),
  IconInfo(name: "git-compare-16", icon: OctIcons.git_compare_16, size: 16),
  IconInfo(name: "git-compare-24", icon: OctIcons.git_compare_24, size: 24),
  IconInfo(name: "git-merge-16", icon: OctIcons.git_merge_16, size: 16),
  IconInfo(name: "git-merge-24", icon: OctIcons.git_merge_24, size: 24),
  IconInfo(
      name: "git-merge-queue-16", icon: OctIcons.git_merge_queue_16, size: 16),
  IconInfo(
      name: "git-merge-queue-24", icon: OctIcons.git_merge_queue_24, size: 24),
  IconInfo(
      name: "git-pull-request-16",
      icon: OctIcons.git_pull_request_16,
      size: 16),
  IconInfo(
      name: "git-pull-request-24",
      icon: OctIcons.git_pull_request_24,
      size: 24),
  IconInfo(
      name: "git-pull-request-closed-16",
      icon: OctIcons.git_pull_request_closed_16,
      size: 16),
  IconInfo(
      name: "git-pull-request-closed-24",
      icon: OctIcons.git_pull_request_closed_24,
      size: 24),
  IconInfo(
      name: "git-pull-request-draft-16",
      icon: OctIcons.git_pull_request_draft_16,
      size: 16),
  IconInfo(
      name: "git-pull-request-draft-24",
      icon: OctIcons.git_pull_request_draft_24,
      size: 24),
  IconInfo(name: "globe-16", icon: OctIcons.globe_16, size: 16),
  IconInfo(name: "globe-24", icon: OctIcons.globe_24, size: 24),
  IconInfo(name: "goal-16", icon: OctIcons.goal_16, size: 16),
  IconInfo(name: "goal-24", icon: OctIcons.goal_24, size: 24),
  IconInfo(name: "grabber-16", icon: OctIcons.grabber_16, size: 16),
  IconInfo(name: "grabber-24", icon: OctIcons.grabber_24, size: 24),
  IconInfo(name: "graph-16", icon: OctIcons.graph_16, size: 16),
  IconInfo(name: "graph-24", icon: OctIcons.graph_24, size: 24),
  IconInfo(name: "hash-16", icon: OctIcons.hash_16, size: 16),
  IconInfo(name: "hash-24", icon: OctIcons.hash_24, size: 24),
  IconInfo(name: "heading-16", icon: OctIcons.heading_16, size: 16),
  IconInfo(name: "heading-24", icon: OctIcons.heading_24, size: 24),
  IconInfo(name: "heart-16", icon: OctIcons.heart_16, size: 16),
  IconInfo(name: "heart-24", icon: OctIcons.heart_24, size: 24),
  IconInfo(name: "heart-fill-16", icon: OctIcons.heart_fill_16, size: 16),
  IconInfo(name: "heart-fill-24", icon: OctIcons.heart_fill_24, size: 24),
  IconInfo(name: "history-16", icon: OctIcons.history_16, size: 16),
  IconInfo(name: "history-24", icon: OctIcons.history_24, size: 24),
  IconInfo(name: "home-16", icon: OctIcons.home_16, size: 16),
  IconInfo(name: "home-24", icon: OctIcons.home_24, size: 24),
  IconInfo(name: "home-fill-16", icon: OctIcons.home_fill_16, size: 16),
  IconInfo(name: "home-fill-24", icon: OctIcons.home_fill_24, size: 24),
  IconInfo(
      name: "horizontal-rule-16", icon: OctIcons.horizontal_rule_16, size: 16),
  IconInfo(
      name: "horizontal-rule-24", icon: OctIcons.horizontal_rule_24, size: 24),
  IconInfo(name: "hourglass-16", icon: OctIcons.hourglass_16, size: 16),
  IconInfo(name: "hourglass-24", icon: OctIcons.hourglass_24, size: 24),
  IconInfo(name: "hubot-16", icon: OctIcons.hubot_16, size: 16),
  IconInfo(name: "hubot-24", icon: OctIcons.hubot_24, size: 24),
  IconInfo(name: "id-badge-16", icon: OctIcons.id_badge_16, size: 16),
  IconInfo(name: "id-badge-24", icon: OctIcons.id_badge_24, size: 24),
  IconInfo(name: "image-16", icon: OctIcons.image_16, size: 16),
  IconInfo(name: "image-24", icon: OctIcons.image_24, size: 24),
  IconInfo(name: "inbox-16", icon: OctIcons.inbox_16, size: 16),
  IconInfo(name: "inbox-24", icon: OctIcons.inbox_24, size: 24),
  IconInfo(name: "infinity-16", icon: OctIcons.infinity_16, size: 16),
  IconInfo(name: "infinity-24", icon: OctIcons.infinity_24, size: 24),
  IconInfo(name: "info-16", icon: OctIcons.info_16, size: 16),
  IconInfo(name: "info-24", icon: OctIcons.info_24, size: 24),
  IconInfo(name: "issue-closed-16", icon: OctIcons.issue_closed_16, size: 16),
  IconInfo(name: "issue-closed-24", icon: OctIcons.issue_closed_24, size: 24),
  IconInfo(name: "issue-draft-16", icon: OctIcons.issue_draft_16, size: 16),
  IconInfo(name: "issue-draft-24", icon: OctIcons.issue_draft_24, size: 24),
  IconInfo(name: "issue-opened-16", icon: OctIcons.issue_opened_16, size: 16),
  IconInfo(name: "issue-opened-24", icon: OctIcons.issue_opened_24, size: 24),
  IconInfo(
      name: "issue-reopened-16", icon: OctIcons.issue_reopened_16, size: 16),
  IconInfo(
      name: "issue-reopened-24", icon: OctIcons.issue_reopened_24, size: 24),
  IconInfo(
      name: "issue-tracked-by-16",
      icon: OctIcons.issue_tracked_by_16,
      size: 16),
  IconInfo(
      name: "issue-tracked-by-24",
      icon: OctIcons.issue_tracked_by_24,
      size: 24),
  IconInfo(name: "issue-tracks-16", icon: OctIcons.issue_tracks_16, size: 16),
  IconInfo(name: "issue-tracks-24", icon: OctIcons.issue_tracks_24, size: 24),
  IconInfo(name: "italic-16", icon: OctIcons.italic_16, size: 16),
  IconInfo(name: "italic-24", icon: OctIcons.italic_24, size: 24),
  IconInfo(name: "iterations-16", icon: OctIcons.iterations_16, size: 16),
  IconInfo(name: "iterations-24", icon: OctIcons.iterations_24, size: 24),
  IconInfo(
      name: "kebab-horizontal-16",
      icon: OctIcons.kebab_horizontal_16,
      size: 16),
  IconInfo(
      name: "kebab-horizontal-24",
      icon: OctIcons.kebab_horizontal_24,
      size: 24),
  IconInfo(name: "key-16", icon: OctIcons.key_16, size: 16),
  IconInfo(name: "key-24", icon: OctIcons.key_24, size: 24),
  IconInfo(name: "key-asterisk-16", icon: OctIcons.key_asterisk_16, size: 16),
  IconInfo(name: "key-asterisk-24", icon: OctIcons.key_asterisk_24, size: 24),
  IconInfo(name: "law-16", icon: OctIcons.law_16, size: 16),
  IconInfo(name: "law-24", icon: OctIcons.law_24, size: 24),
  IconInfo(name: "light-bulb-16", icon: OctIcons.light_bulb_16, size: 16),
  IconInfo(name: "light-bulb-24", icon: OctIcons.light_bulb_24, size: 24),
  IconInfo(name: "link-16", icon: OctIcons.link_16, size: 16),
  IconInfo(name: "link-24", icon: OctIcons.link_24, size: 24),
  IconInfo(name: "link-external-16", icon: OctIcons.link_external_16, size: 16),
  IconInfo(name: "link-external-24", icon: OctIcons.link_external_24, size: 24),
  IconInfo(name: "list-ordered-16", icon: OctIcons.list_ordered_16, size: 16),
  IconInfo(name: "list-ordered-24", icon: OctIcons.list_ordered_24, size: 24),
  IconInfo(
      name: "list-unordered-16", icon: OctIcons.list_unordered_16, size: 16),
  IconInfo(
      name: "list-unordered-24", icon: OctIcons.list_unordered_24, size: 24),
  IconInfo(name: "location-16", icon: OctIcons.location_16, size: 16),
  IconInfo(name: "location-24", icon: OctIcons.location_24, size: 24),
  IconInfo(name: "lock-16", icon: OctIcons.lock_16, size: 16),
  IconInfo(name: "lock-24", icon: OctIcons.lock_24, size: 24),
  IconInfo(name: "log-16", icon: OctIcons.log_16, size: 16),
  IconInfo(name: "log-24", icon: OctIcons.log_24, size: 24),
  IconInfo(name: "logo-gist-16", icon: OctIcons.logo_gist_16, size: 16),
  IconInfo(name: "logo-gist-24", icon: OctIcons.logo_gist_24, size: 24),
  IconInfo(name: "logo-github-16", icon: OctIcons.logo_github_16, size: 16),
  IconInfo(name: "logo-github-24", icon: OctIcons.logo_github_24, size: 24),
  IconInfo(name: "mail-16", icon: OctIcons.mail_16, size: 16),
  IconInfo(name: "mail-24", icon: OctIcons.mail_24, size: 24),
  IconInfo(name: "mark-github-16", icon: OctIcons.mark_github_16, size: 16),
  IconInfo(name: "mark-github-24", icon: OctIcons.mark_github_24, size: 24),
  IconInfo(name: "markdown-16", icon: OctIcons.markdown_16, size: 16),
  IconInfo(name: "markdown-24", icon: OctIcons.markdown_24, size: 24),
  IconInfo(name: "megaphone-16", icon: OctIcons.megaphone_16, size: 16),
  IconInfo(name: "megaphone-24", icon: OctIcons.megaphone_24, size: 24),
  IconInfo(name: "mention-16", icon: OctIcons.mention_16, size: 16),
  IconInfo(name: "mention-24", icon: OctIcons.mention_24, size: 24),
  IconInfo(name: "meter-16", icon: OctIcons.meter_16, size: 16),
  IconInfo(name: "meter-24", icon: OctIcons.meter_24, size: 24),
  IconInfo(name: "milestone-16", icon: OctIcons.milestone_16, size: 16),
  IconInfo(name: "milestone-24", icon: OctIcons.milestone_24, size: 24),
  IconInfo(name: "mirror-16", icon: OctIcons.mirror_16, size: 16),
  IconInfo(name: "mirror-24", icon: OctIcons.mirror_24, size: 24),
  IconInfo(name: "moon-16", icon: OctIcons.moon_16, size: 16),
  IconInfo(name: "moon-24", icon: OctIcons.moon_24, size: 24),
  IconInfo(name: "mortar-board-16", icon: OctIcons.mortar_board_16, size: 16),
  IconInfo(name: "mortar-board-24", icon: OctIcons.mortar_board_24, size: 24),
  IconInfo(
      name: "move-to-bottom-16", icon: OctIcons.move_to_bottom_16, size: 16),
  IconInfo(
      name: "move-to-bottom-24", icon: OctIcons.move_to_bottom_24, size: 24),
  IconInfo(name: "move-to-end-16", icon: OctIcons.move_to_end_16, size: 16),
  IconInfo(name: "move-to-end-24", icon: OctIcons.move_to_end_24, size: 24),
  IconInfo(name: "move-to-start-16", icon: OctIcons.move_to_start_16, size: 16),
  IconInfo(name: "move-to-start-24", icon: OctIcons.move_to_start_24, size: 24),
  IconInfo(name: "move-to-top-16", icon: OctIcons.move_to_top_16, size: 16),
  IconInfo(name: "move-to-top-24", icon: OctIcons.move_to_top_24, size: 24),
  IconInfo(name: "multi-select-16", icon: OctIcons.multi_select_16, size: 16),
  IconInfo(name: "multi-select-24", icon: OctIcons.multi_select_24, size: 24),
  IconInfo(name: "mute-16", icon: OctIcons.mute_16, size: 16),
  IconInfo(name: "mute-24", icon: OctIcons.mute_24, size: 24),
  IconInfo(name: "no-entry-16", icon: OctIcons.no_entry_16, size: 16),
  IconInfo(name: "no-entry-24", icon: OctIcons.no_entry_24, size: 24),
  IconInfo(name: "no-entry-fill-12", icon: OctIcons.no_entry_fill_12, size: 12),
  IconInfo(name: "north-star-16", icon: OctIcons.north_star_16, size: 16),
  IconInfo(name: "north-star-24", icon: OctIcons.north_star_24, size: 24),
  IconInfo(name: "note-16", icon: OctIcons.note_16, size: 16),
  IconInfo(name: "note-24", icon: OctIcons.note_24, size: 24),
  IconInfo(name: "number-16", icon: OctIcons.number_16, size: 16),
  IconInfo(name: "number-24", icon: OctIcons.number_24, size: 24),
  IconInfo(name: "organization-16", icon: OctIcons.organization_16, size: 16),
  IconInfo(name: "organization-24", icon: OctIcons.organization_24, size: 24),
  IconInfo(name: "package-16", icon: OctIcons.package_16, size: 16),
  IconInfo(name: "package-24", icon: OctIcons.package_24, size: 24),
  IconInfo(
      name: "package-dependencies-16",
      icon: OctIcons.package_dependencies_16,
      size: 16),
  IconInfo(
      name: "package-dependencies-24",
      icon: OctIcons.package_dependencies_24,
      size: 24),
  IconInfo(
      name: "package-dependents-16",
      icon: OctIcons.package_dependents_16,
      size: 16),
  IconInfo(
      name: "package-dependents-24",
      icon: OctIcons.package_dependents_24,
      size: 24),
  IconInfo(name: "paintbrush-16", icon: OctIcons.paintbrush_16, size: 16),
  IconInfo(name: "paintbrush-24", icon: OctIcons.paintbrush_24, size: 24),
  IconInfo(
      name: "paper-airplane-16", icon: OctIcons.paper_airplane_16, size: 16),
  IconInfo(
      name: "paper-airplane-24", icon: OctIcons.paper_airplane_24, size: 24),
  IconInfo(name: "paperclip-16", icon: OctIcons.paperclip_16, size: 16),
  IconInfo(name: "paperclip-24", icon: OctIcons.paperclip_24, size: 24),
  IconInfo(name: "passkey-fill-16", icon: OctIcons.passkey_fill_16, size: 16),
  IconInfo(name: "passkey-fill-24", icon: OctIcons.passkey_fill_24, size: 24),
  IconInfo(name: "paste-16", icon: OctIcons.paste_16, size: 16),
  IconInfo(name: "paste-24", icon: OctIcons.paste_24, size: 24),
  IconInfo(name: "pencil-16", icon: OctIcons.pencil_16, size: 16),
  IconInfo(name: "pencil-24", icon: OctIcons.pencil_24, size: 24),
  IconInfo(name: "people-16", icon: OctIcons.people_16, size: 16),
  IconInfo(name: "people-24", icon: OctIcons.people_24, size: 24),
  IconInfo(name: "person-16", icon: OctIcons.person_16, size: 16),
  IconInfo(name: "person-24", icon: OctIcons.person_24, size: 24),
  IconInfo(name: "person-add-16", icon: OctIcons.person_add_16, size: 16),
  IconInfo(name: "person-add-24", icon: OctIcons.person_add_24, size: 24),
  IconInfo(name: "person-fill-16", icon: OctIcons.person_fill_16, size: 16),
  IconInfo(name: "person-fill-24", icon: OctIcons.person_fill_24, size: 24),
  IconInfo(name: "pin-16", icon: OctIcons.pin_16, size: 16),
  IconInfo(name: "pin-24", icon: OctIcons.pin_24, size: 24),
  IconInfo(name: "pin-slash-16", icon: OctIcons.pin_slash_16, size: 16),
  IconInfo(name: "pin-slash-24", icon: OctIcons.pin_slash_24, size: 24),
  IconInfo(name: "pivot-column-16", icon: OctIcons.pivot_column_16, size: 16),
  IconInfo(name: "pivot-column-24", icon: OctIcons.pivot_column_24, size: 24),
  IconInfo(name: "play-16", icon: OctIcons.play_16, size: 16),
  IconInfo(name: "play-24", icon: OctIcons.play_24, size: 24),
  IconInfo(name: "plug-16", icon: OctIcons.plug_16, size: 16),
  IconInfo(name: "plug-24", icon: OctIcons.plug_24, size: 24),
  IconInfo(name: "plus-16", icon: OctIcons.plus_16, size: 16),
  IconInfo(name: "plus-24", icon: OctIcons.plus_24, size: 24),
  IconInfo(name: "plus-circle-16", icon: OctIcons.plus_circle_16, size: 16),
  IconInfo(name: "plus-circle-24", icon: OctIcons.plus_circle_24, size: 24),
  IconInfo(name: "project-16", icon: OctIcons.project_16, size: 16),
  IconInfo(name: "project-24", icon: OctIcons.project_24, size: 24),
  IconInfo(
      name: "project-roadmap-16", icon: OctIcons.project_roadmap_16, size: 16),
  IconInfo(
      name: "project-roadmap-24", icon: OctIcons.project_roadmap_24, size: 24),
  IconInfo(
      name: "project-symlink-16", icon: OctIcons.project_symlink_16, size: 16),
  IconInfo(
      name: "project-symlink-24", icon: OctIcons.project_symlink_24, size: 24),
  IconInfo(
      name: "project-template-16",
      icon: OctIcons.project_template_16,
      size: 16),
  IconInfo(
      name: "project-template-24",
      icon: OctIcons.project_template_24,
      size: 24),
  IconInfo(name: "pulse-16", icon: OctIcons.pulse_16, size: 16),
  IconInfo(name: "pulse-24", icon: OctIcons.pulse_24, size: 24),
  IconInfo(name: "question-16", icon: OctIcons.question_16, size: 16),
  IconInfo(name: "question-24", icon: OctIcons.question_24, size: 24),
  IconInfo(name: "quote-16", icon: OctIcons.quote_16, size: 16),
  IconInfo(name: "quote-24", icon: OctIcons.quote_24, size: 24),
  IconInfo(name: "read-16", icon: OctIcons.read_16, size: 16),
  IconInfo(name: "read-24", icon: OctIcons.read_24, size: 24),
  IconInfo(name: "redo-16", icon: OctIcons.redo_16, size: 16),
  IconInfo(name: "redo-24", icon: OctIcons.redo_24, size: 24),
  IconInfo(name: "rel-file-path-16", icon: OctIcons.rel_file_path_16, size: 16),
  IconInfo(name: "rel-file-path-24", icon: OctIcons.rel_file_path_24, size: 24),
  IconInfo(name: "reply-16", icon: OctIcons.reply_16, size: 16),
  IconInfo(name: "reply-24", icon: OctIcons.reply_24, size: 24),
  IconInfo(name: "repo-16", icon: OctIcons.repo_16, size: 16),
  IconInfo(name: "repo-24", icon: OctIcons.repo_24, size: 24),
  IconInfo(name: "repo-clone-16", icon: OctIcons.repo_clone_16, size: 16),
  IconInfo(name: "repo-clone-24", icon: OctIcons.repo_clone_24, size: 24),
  IconInfo(name: "repo-delete-24", icon: OctIcons.repo_delete_24, size: 24),
  IconInfo(name: "repo-deleted-16", icon: OctIcons.repo_deleted_16, size: 16),
  IconInfo(name: "repo-forked-16", icon: OctIcons.repo_forked_16, size: 16),
  IconInfo(name: "repo-forked-24", icon: OctIcons.repo_forked_24, size: 24),
  IconInfo(name: "repo-locked-16", icon: OctIcons.repo_locked_16, size: 16),
  IconInfo(name: "repo-locked-24", icon: OctIcons.repo_locked_24, size: 24),
  IconInfo(name: "repo-pull-16", icon: OctIcons.repo_pull_16, size: 16),
  IconInfo(name: "repo-pull-24", icon: OctIcons.repo_pull_24, size: 24),
  IconInfo(name: "repo-push-16", icon: OctIcons.repo_push_16, size: 16),
  IconInfo(name: "repo-push-24", icon: OctIcons.repo_push_24, size: 24),
  IconInfo(name: "repo-template-16", icon: OctIcons.repo_template_16, size: 16),
  IconInfo(name: "repo-template-24", icon: OctIcons.repo_template_24, size: 24),
  IconInfo(name: "report-16", icon: OctIcons.report_16, size: 16),
  IconInfo(name: "report-24", icon: OctIcons.report_24, size: 24),
  IconInfo(name: "rocket-16", icon: OctIcons.rocket_16, size: 16),
  IconInfo(name: "rocket-24", icon: OctIcons.rocket_24, size: 24),
  IconInfo(name: "rows-16", icon: OctIcons.rows_16, size: 16),
  IconInfo(name: "rows-24", icon: OctIcons.rows_24, size: 24),
  IconInfo(name: "rss-16", icon: OctIcons.rss_16, size: 16),
  IconInfo(name: "rss-24", icon: OctIcons.rss_24, size: 24),
  IconInfo(name: "ruby-16", icon: OctIcons.ruby_16, size: 16),
  IconInfo(name: "ruby-24", icon: OctIcons.ruby_24, size: 24),
  IconInfo(name: "screen-full-16", icon: OctIcons.screen_full_16, size: 16),
  IconInfo(name: "screen-full-24", icon: OctIcons.screen_full_24, size: 24),
  IconInfo(name: "screen-normal-16", icon: OctIcons.screen_normal_16, size: 16),
  IconInfo(name: "screen-normal-24", icon: OctIcons.screen_normal_24, size: 24),
  IconInfo(name: "search-16", icon: OctIcons.search_16, size: 16),
  IconInfo(name: "search-24", icon: OctIcons.search_24, size: 24),
  IconInfo(name: "server-16", icon: OctIcons.server_16, size: 16),
  IconInfo(name: "server-24", icon: OctIcons.server_24, size: 24),
  IconInfo(name: "share-16", icon: OctIcons.share_16, size: 16),
  IconInfo(name: "share-24", icon: OctIcons.share_24, size: 24),
  IconInfo(name: "share-android-16", icon: OctIcons.share_android_16, size: 16),
  IconInfo(name: "share-android-24", icon: OctIcons.share_android_24, size: 24),
  IconInfo(name: "shield-16", icon: OctIcons.shield_16, size: 16),
  IconInfo(name: "shield-24", icon: OctIcons.shield_24, size: 24),
  IconInfo(name: "shield-check-16", icon: OctIcons.shield_check_16, size: 16),
  IconInfo(name: "shield-check-24", icon: OctIcons.shield_check_24, size: 24),
  IconInfo(name: "shield-lock-16", icon: OctIcons.shield_lock_16, size: 16),
  IconInfo(name: "shield-lock-24", icon: OctIcons.shield_lock_24, size: 24),
  IconInfo(name: "shield-slash-16", icon: OctIcons.shield_slash_16, size: 16),
  IconInfo(name: "shield-slash-24", icon: OctIcons.shield_slash_24, size: 24),
  IconInfo(name: "shield-x-16", icon: OctIcons.shield_x_16, size: 16),
  IconInfo(name: "shield-x-24", icon: OctIcons.shield_x_24, size: 24),
  IconInfo(
      name: "sidebar-collapse-16",
      icon: OctIcons.sidebar_collapse_16,
      size: 16),
  IconInfo(
      name: "sidebar-collapse-24",
      icon: OctIcons.sidebar_collapse_24,
      size: 24),
  IconInfo(
      name: "sidebar-expand-16", icon: OctIcons.sidebar_expand_16, size: 16),
  IconInfo(
      name: "sidebar-expand-24", icon: OctIcons.sidebar_expand_24, size: 24),
  IconInfo(name: "sign-in-16", icon: OctIcons.sign_in_16, size: 16),
  IconInfo(name: "sign-in-24", icon: OctIcons.sign_in_24, size: 24),
  IconInfo(name: "sign-out-16", icon: OctIcons.sign_out_16, size: 16),
  IconInfo(name: "sign-out-24", icon: OctIcons.sign_out_24, size: 24),
  IconInfo(name: "single-select-16", icon: OctIcons.single_select_16, size: 16),
  IconInfo(name: "single-select-24", icon: OctIcons.single_select_24, size: 24),
  IconInfo(name: "skip-16", icon: OctIcons.skip_16, size: 16),
  IconInfo(name: "skip-24", icon: OctIcons.skip_24, size: 24),
  IconInfo(name: "skip-fill-16", icon: OctIcons.skip_fill_16, size: 16),
  IconInfo(name: "skip-fill-24", icon: OctIcons.skip_fill_24, size: 24),
  IconInfo(name: "sliders-16", icon: OctIcons.sliders_16, size: 16),
  IconInfo(name: "sliders-24", icon: OctIcons.sliders_24, size: 24),
  IconInfo(name: "smiley-16", icon: OctIcons.smiley_16, size: 16),
  IconInfo(name: "smiley-24", icon: OctIcons.smiley_24, size: 24),
  IconInfo(name: "sort-asc-16", icon: OctIcons.sort_asc_16, size: 16),
  IconInfo(name: "sort-asc-24", icon: OctIcons.sort_asc_24, size: 24),
  IconInfo(name: "sort-desc-16", icon: OctIcons.sort_desc_16, size: 16),
  IconInfo(name: "sort-desc-24", icon: OctIcons.sort_desc_24, size: 24),
  IconInfo(name: "sparkle-fill-16", icon: OctIcons.sparkle_fill_16, size: 16),
  IconInfo(name: "sparkle-fill-24", icon: OctIcons.sparkle_fill_24, size: 24),
  IconInfo(name: "sparkles-fill-16", icon: OctIcons.sparkles_fill_16, size: 16),
  IconInfo(name: "sparkles-fill-24", icon: OctIcons.sparkles_fill_24, size: 24),
  IconInfo(name: "sponsor-tiers-16", icon: OctIcons.sponsor_tiers_16, size: 16),
  IconInfo(name: "sponsor-tiers-24", icon: OctIcons.sponsor_tiers_24, size: 24),
  IconInfo(name: "square-16", icon: OctIcons.square_16, size: 16),
  IconInfo(name: "square-24", icon: OctIcons.square_24, size: 24),
  IconInfo(name: "square-circle-16", icon: OctIcons.square_circle_16, size: 16),
  IconInfo(name: "square-circle-24", icon: OctIcons.square_circle_24, size: 24),
  IconInfo(name: "square-fill-16", icon: OctIcons.square_fill_16, size: 16),
  IconInfo(name: "square-fill-24", icon: OctIcons.square_fill_24, size: 24),
  IconInfo(name: "squirrel-16", icon: OctIcons.squirrel_16, size: 16),
  IconInfo(name: "squirrel-24", icon: OctIcons.squirrel_24, size: 24),
  IconInfo(name: "stack-16", icon: OctIcons.stack_16, size: 16),
  IconInfo(name: "stack-24", icon: OctIcons.stack_24, size: 24),
  IconInfo(name: "star-16", icon: OctIcons.star_16, size: 16),
  IconInfo(name: "star-24", icon: OctIcons.star_24, size: 24),
  IconInfo(name: "star-fill-16", icon: OctIcons.star_fill_16, size: 16),
  IconInfo(name: "star-fill-24", icon: OctIcons.star_fill_24, size: 24),
  IconInfo(name: "stop-16", icon: OctIcons.stop_16, size: 16),
  IconInfo(name: "stop-24", icon: OctIcons.stop_24, size: 24),
  IconInfo(name: "stopwatch-16", icon: OctIcons.stopwatch_16, size: 16),
  IconInfo(name: "stopwatch-24", icon: OctIcons.stopwatch_24, size: 24),
  IconInfo(name: "strikethrough-16", icon: OctIcons.strikethrough_16, size: 16),
  IconInfo(name: "strikethrough-24", icon: OctIcons.strikethrough_24, size: 24),
  IconInfo(name: "sun-16", icon: OctIcons.sun_16, size: 16),
  IconInfo(name: "sun-24", icon: OctIcons.sun_24, size: 24),
  IconInfo(name: "sync-16", icon: OctIcons.sync_16, size: 16),
  IconInfo(name: "sync-24", icon: OctIcons.sync_24, size: 24),
  IconInfo(name: "tab-16", icon: OctIcons.tab_16, size: 16),
  IconInfo(name: "tab-24", icon: OctIcons.tab_24, size: 24),
  IconInfo(name: "tab-external-16", icon: OctIcons.tab_external_16, size: 16),
  IconInfo(name: "tab-external-24", icon: OctIcons.tab_external_24, size: 24),
  IconInfo(name: "table-16", icon: OctIcons.table_16, size: 16),
  IconInfo(name: "table-24", icon: OctIcons.table_24, size: 24),
  IconInfo(name: "tag-16", icon: OctIcons.tag_16, size: 16),
  IconInfo(name: "tag-24", icon: OctIcons.tag_24, size: 24),
  IconInfo(name: "tasklist-16", icon: OctIcons.tasklist_16, size: 16),
  IconInfo(name: "tasklist-24", icon: OctIcons.tasklist_24, size: 24),
  IconInfo(name: "telescope-16", icon: OctIcons.telescope_16, size: 16),
  IconInfo(name: "telescope-24", icon: OctIcons.telescope_24, size: 24),
  IconInfo(
      name: "telescope-fill-16", icon: OctIcons.telescope_fill_16, size: 16),
  IconInfo(
      name: "telescope-fill-24", icon: OctIcons.telescope_fill_24, size: 24),
  IconInfo(name: "terminal-16", icon: OctIcons.terminal_16, size: 16),
  IconInfo(name: "terminal-24", icon: OctIcons.terminal_24, size: 24),
  IconInfo(name: "three-bars-16", icon: OctIcons.three_bars_16, size: 16),
  IconInfo(name: "three-bars-24", icon: OctIcons.three_bars_24, size: 24),
  IconInfo(name: "thumbsdown-16", icon: OctIcons.thumbsdown_16, size: 16),
  IconInfo(name: "thumbsdown-24", icon: OctIcons.thumbsdown_24, size: 24),
  IconInfo(name: "thumbsup-16", icon: OctIcons.thumbsup_16, size: 16),
  IconInfo(name: "thumbsup-24", icon: OctIcons.thumbsup_24, size: 24),
  IconInfo(name: "tools-16", icon: OctIcons.tools_16, size: 16),
  IconInfo(name: "tools-24", icon: OctIcons.tools_24, size: 24),
  IconInfo(
      name: "tracked-by-closed-completed-16",
      icon: OctIcons.tracked_by_closed_completed_16,
      size: 16),
  IconInfo(
      name: "tracked-by-closed-completed-24",
      icon: OctIcons.tracked_by_closed_completed_24,
      size: 24),
  IconInfo(
      name: "tracked-by-closed-not-planned-16",
      icon: OctIcons.tracked_by_closed_not_planned_16,
      size: 16),
  IconInfo(
      name: "tracked-by-closed-not-planned-24",
      icon: OctIcons.tracked_by_closed_not_planned_24,
      size: 24),
  IconInfo(name: "trash-16", icon: OctIcons.trash_16, size: 16),
  IconInfo(name: "trash-24", icon: OctIcons.trash_24, size: 24),
  IconInfo(name: "triangle-down-16", icon: OctIcons.triangle_down_16, size: 16),
  IconInfo(name: "triangle-down-24", icon: OctIcons.triangle_down_24, size: 24),
  IconInfo(name: "triangle-left-16", icon: OctIcons.triangle_left_16, size: 16),
  IconInfo(name: "triangle-left-24", icon: OctIcons.triangle_left_24, size: 24),
  IconInfo(
      name: "triangle-right-16", icon: OctIcons.triangle_right_16, size: 16),
  IconInfo(
      name: "triangle-right-24", icon: OctIcons.triangle_right_24, size: 24),
  IconInfo(name: "triangle-up-16", icon: OctIcons.triangle_up_16, size: 16),
  IconInfo(name: "triangle-up-24", icon: OctIcons.triangle_up_24, size: 24),
  IconInfo(name: "trophy-16", icon: OctIcons.trophy_16, size: 16),
  IconInfo(name: "trophy-24", icon: OctIcons.trophy_24, size: 24),
  IconInfo(name: "typography-16", icon: OctIcons.typography_16, size: 16),
  IconInfo(name: "typography-24", icon: OctIcons.typography_24, size: 24),
  IconInfo(name: "undo-16", icon: OctIcons.undo_16, size: 16),
  IconInfo(name: "undo-24", icon: OctIcons.undo_24, size: 24),
  IconInfo(name: "unfold-16", icon: OctIcons.unfold_16, size: 16),
  IconInfo(name: "unfold-24", icon: OctIcons.unfold_24, size: 24),
  IconInfo(name: "unlink-16", icon: OctIcons.unlink_16, size: 16),
  IconInfo(name: "unlink-24", icon: OctIcons.unlink_24, size: 24),
  IconInfo(name: "unlock-16", icon: OctIcons.unlock_16, size: 16),
  IconInfo(name: "unlock-24", icon: OctIcons.unlock_24, size: 24),
  IconInfo(name: "unmute-16", icon: OctIcons.unmute_16, size: 16),
  IconInfo(name: "unmute-24", icon: OctIcons.unmute_24, size: 24),
  IconInfo(name: "unread-16", icon: OctIcons.unread_16, size: 16),
  IconInfo(name: "unread-24", icon: OctIcons.unread_24, size: 24),
  IconInfo(name: "unverified-16", icon: OctIcons.unverified_16, size: 16),
  IconInfo(name: "unverified-24", icon: OctIcons.unverified_24, size: 24),
  IconInfo(name: "upload-16", icon: OctIcons.upload_16, size: 16),
  IconInfo(name: "upload-24", icon: OctIcons.upload_24, size: 24),
  IconInfo(name: "verified-16", icon: OctIcons.verified_16, size: 16),
  IconInfo(name: "verified-24", icon: OctIcons.verified_24, size: 24),
  IconInfo(name: "versions-16", icon: OctIcons.versions_16, size: 16),
  IconInfo(name: "versions-24", icon: OctIcons.versions_24, size: 24),
  IconInfo(name: "video-16", icon: OctIcons.video_16, size: 16),
  IconInfo(name: "video-24", icon: OctIcons.video_24, size: 24),
  IconInfo(name: "webhook-16", icon: OctIcons.webhook_16, size: 16),
  IconInfo(name: "workflow-16", icon: OctIcons.workflow_16, size: 16),
  IconInfo(name: "workflow-24", icon: OctIcons.workflow_24, size: 24),
  IconInfo(name: "x-12", icon: OctIcons.x_12, size: 12),
  IconInfo(name: "x-16", icon: OctIcons.x_16, size: 16),
  IconInfo(name: "x-24", icon: OctIcons.x_24, size: 24),
  IconInfo(name: "x-circle-16", icon: OctIcons.x_circle_16, size: 16),
  IconInfo(name: "x-circle-24", icon: OctIcons.x_circle_24, size: 24),
  IconInfo(name: "x-circle-fill-12", icon: OctIcons.x_circle_fill_12, size: 12),
  IconInfo(name: "x-circle-fill-16", icon: OctIcons.x_circle_fill_16, size: 16),
  IconInfo(name: "x-circle-fill-24", icon: OctIcons.x_circle_fill_24, size: 24),
  IconInfo(name: "zap-16", icon: OctIcons.zap_16, size: 16),
  IconInfo(name: "zap-24", icon: OctIcons.zap_24, size: 24),
  IconInfo(name: "zoom-in-16", icon: OctIcons.zoom_in_16, size: 16),
  IconInfo(name: "zoom-in-24", icon: OctIcons.zoom_in_24, size: 24),
  IconInfo(name: "zoom-out-16", icon: OctIcons.zoom_out_16, size: 16),
  IconInfo(name: "zoom-out-24", icon: OctIcons.zoom_out_24, size: 24),
];
